COMP4900_SOCE_WebApp/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;
using System.Net;
using System.Data.Entity;
using COMP4900_SOCE_WebApp.Models;

namespace COMP4900_SOCE_WebApp.Controllers
{
    public class RolesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        //Get: Roles
        public ActionResult Index()
        {
            return View(db.Roles.ToList());
        }

        // GET: Roles/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = db.Roles.Find(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        // GET: Roles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Roles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IdentityRole role)
        {
            if (ModelState.IsValid)
            {
                db.Roles.Add(role);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(role);
        }

        // GET: Roles/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = db.Roles.Find(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        // POST: Roles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(IdentityRole role)
        {
            if (ModelState.IsValid)
            {
                db.Entry(role).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(role);
        }

        // GET: Options/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = db.Roles.Find(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        // POST: Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            var role = db.Roles.Find(id);
            db.Roles.Remove(role);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

COMP4900_SOCE_WebApp/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Net;
using System.Data.Entity;
using COMP4900_SOCE_WebApp.Models;
using SensorDataModel.Models;
using System.Threading.Tasks;
using System.Collections;
using SensorDataModel.Extensions;
using System.Diagnostics;
using System.Data.Entity.Core;
using System.Data.Entity.Infrastructure;

namespace COMP4900_SOCE_WebApp.Controllers
{
    public class UsersController : Controller
    {
        //public UserManager<ApplicationUser> UserManager { get; private set; }
        private ApplicationDbContext db = new ApplicationDbContext();
        
        //Get: Roles
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View(db.Users.ToList());
        }

        // GET: Roles/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Users/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            var roles = db.Roles.ToList();
            List<string> roleList = new List<string>();
            foreach (var role in roles)
            {
                roleList.Add(role.Name);
            }
            ViewBag.RoleDropdownlist = new SelectList(roleList);
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "UserName,Email,fName,lName,PasswordHash")] ApplicationUser user, string roleName)
        {
            var roles = db.Roles.ToList();
            List<string> roleList = new List<string>();
            foreach (var role in roles)
            {
                roleList.Add(role.Name);
            }
            ViewBag.RoleDropdownlist = new SelectList(roleList);

            if (user.PasswordHash != null)
            {
                if (user.PasswordHash.Length < 6)
                {
                    ViewBag.PassLength = "Password must be at least 6 characters";
                    return View(user);
                }
            }
            else
            {
                ViewBag.PassLength = "Password must be at least 6 characters";
                return View(user);
            }

            if (ModelState.IsValid)
            {
                var roleStore = new RoleStore<IdentityRole>(db);
                var userStore = new UserStore<ApplicationUser>(db);
                var userManager = new UserManager<ApplicationUser>(userStore);
                var newUserMake = userManager.FindByName(user.UserName);
                //var checkUser = db.Users.Find(user.UserName);
                if (newUserMake == null)
                {
                    var newUser = new ApplicationUser
                    {
                        UserName = user.UserName.ToUpper(),
                        Email = user.Email,
                        fName = user.fName,
                        lName = user.lName,
                        //PasswordHash = user.PasswordHash,
                        //LockoutEnabled = false,
                        //SecurityStamp = Guid.NewGuid().ToString(),
                        //AccessFailedCount = 1,
                        IsActive = true
                    };
                    
                    var result = userManager.Create(newUser, user.PasswordHash);
                    if (result.Succeeded)
                    {
                        userManager.SetLockoutEnabled(newUser.Id, false);
                        userManager.AddToRole(newUser.Id, roleName);
                    }
                    else
                    {
                        Debug.WriteLine("Cant create user");
                    }
                    //db.Users.Add(newUser);
                    //db.Users.Add(newUser);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            return View(user);
        }

        // GET: Roles/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Roles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "UserName,Email,fName,lName,PasswordHash")] ApplicationUser user, bool isActive)
        {
            if (ModelState.IsValid)
            {
                using (var contxt = new ApplicationDbContext())
                {
                    bool saved;
                    var edit = contxt.Users
                        .Where(m => m.UserName == user.UserName)
                        .FirstOrDefault();
                    edit.fName = user.fName;
                    edit.lName = user.lName;
                    edit.IsActive = isActive;
                    var hash = new PasswordHasher();
                    edit.PasswordHash = hash.HashPassword(user.PasswordHash);
                    edit.Email = user.Email;
                    edit.UserName = user.UserName;
                    do
                    {
                        saved = false;
                        try
                        {
                            //db.Users.Add(user);
                            //contxt.Entry(user).State = EntityState.Modified;
                            contxt.SaveChanges();
                        }
                        catch (DbUpdateConcurrencyException ex)
                        {
                            saved = true;
                            var entries = ex.Entries.Single();
                            entries.OriginalValues.SetValues(entries.GetDatabaseValues());
                            //entries.OriginalValues.SetValues(entries.GetDatabaseValues());
                        }
                    } while (saved);
                }
                
                //db.Users.Attach(user);
                //user.IsActive = isActive;
                //db.Entry(user).State = EntityState.Modified;
                //ctx.Entry(user).Property(i => i.UserName).IsModified = true;
                //ctx.Entry(user).Property(i => i.Email).IsModified = true;
                //ctx.Entry(user).Property(i => i.fName).IsModified = true;
                //ctx.Entry(user).Property(i => i.lName).IsModified = true;
                //ctx.Entry(user).Property(i => i.PasswordHash).IsModified = true;
                //ctx.Entry(user).Property(i => i.IsActive).IsModified = true;
                //db.SaveChanges();



                //ApplicationUser u = UserManager.FindById(user.id);
                //db.Entry(user).State = EntityState.Modified;
                //db.Entry(user).Property(i => i.UserName).IsModified = true;
                //db.Entry(user).Property(i => i.Email).IsModified = true;
                //db.Entry(user).Property(i => i.fName).IsModified = true;
                //db.Entry(user).Property(i => i.lName).IsModified = true;
                //db.Entry(user).Property(i => i.PasswordHash).IsModified = true;
                //db.Entry(user).Property(i => i.IsActive).IsModified = true;
                //db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: Options/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(string id)
        {
            var user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //var user = db.Users.Find(id);

            return View(user);
        }

        // POST: Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(string id)
        {
            //var user = db.Roles.Find(id);
            //db.Roles.Remove(user);
            var userActive = db.Users.Find(id);
            userActive.IsActive = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Roles/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult LockOut(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Roles/LockOut/5

COMP4900_SOCE_WebApp/Views/Users/Create.cshtml
@*@model Microsoft.AspNet.Identity.EntityFramework.IdentityUser*@
@model COMP4900_SOCE_WebApp.Models.ApplicationUser

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
<input type="submit" value="Back" class="btn btn-default" onclick="location.href='@Url.Action("Index", "Users")'"><br />
@if (ViewBag.PassLength != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.PassLength
    </div>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.AccessFailedCount)
        @Html.HiddenFor(model => model.EmailConfirmed)
        @Html.HiddenFor(model => model.LockoutEnabled)
        @Html.HiddenFor(model => model.PhoneNumber)
        @Html.HiddenFor(model => model.PhoneNumberConfirmed)
        @Html.HiddenFor(model => model.SecurityStamp)
        @Html.HiddenFor(model => model.TwoFactorEnabled)
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PasswordHash, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.PasswordFor(model => model.PasswordHash, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.EditorFor(model => model.PasswordHash, new { htmlAttributes = new { @class = "form-control" } }) <div class="alert alert-info" role="alert" style="display:inline-block;">(Must be 6+ characters)</div>
                @Html.ValidationMessageFor(model => model.PasswordHash, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lName, "", new { @class = "text-danger" })
            </div>
        </div>

        @using (Html.BeginForm("Create", "Users"))
        {
            <div class="form-group">
                <div class="control-label col-md-2">Role Name:</div>
                <div class="col-md-10">
                    @Html.DropDownList("RoleName", (IEnumerable<SelectListItem>)ViewBag.RoleDropdownlist, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

COMP4900_SOCE_WebApp/Views/Users/Delete.cshtml
@model COMP4900_SOCE_WebApp.Models.ApplicationUser

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ApplicationUser</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailConfirmed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailConfirmed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PasswordHash)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PasswordHash)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecurityStamp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecurityStamp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumberConfirmed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumberConfirmed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TwoFactorEnabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TwoFactorEnabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LockoutEndDateUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LockoutEndDateUtc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LockoutEnabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LockoutEnabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccessFailedCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccessFailedCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

COMP4900_SOCE_WebApp/Views/Users/Details.cshtml
@model COMP4900_SOCE_WebApp.Models.ApplicationUser

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ApplicationUser</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailConfirmed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailConfirmed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PasswordHash)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PasswordHash)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecurityStamp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecurityStamp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumberConfirmed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumberConfirmed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TwoFactorEnabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TwoFactorEnabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LockoutEndDateUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LockoutEndDateUtc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LockoutEnabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LockoutEnabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccessFailedCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccessFailedCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Delete User", "DeleteConfirmed", new { id = Model.UserName }) |
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |*@
    @Html.ActionLink("Back to List", "Index")
</p>

COMP4900_SOCE_WebApp/Views/Users/Index.cshtml
@*@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityUser>*@
@*@model IEnumerable<COMP4900_SOCE_WebApp.Models.RegisterViewModel>*@
@model IEnumerable<COMP4900_SOCE_WebApp.Models.ApplicationUser>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
<input type="submit" value="Manage User Roles" class="btn btn - info - outline" onclick="location.href='@Url.Action("ManageUserRoles", "Users")'">
<input type="submit" value="Add New User" class="btn btn-success - outline" onclick="location.href='@Url.Action("Create", "Users")'">
@*@Html.ActionLink("Manage User Role", "ManageUserRoles", null, new { @class = "btn btn - info - outline" })
@Html.ActionLink("Add New User", "Create", null, new { @class = "btn btn - success - outline" })*@


<table class="table">
    <tr>
        <th hidden>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.lName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.Roles)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <th hidden>
                @Html.DisplayFor(modelItem => item.Id)    
            </th>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.fName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.lName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td hidden>
                @Html.DisplayFor(modelItem => item.Roles)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @*@Html.ActionLink("LockOut", "LockOut", new { id = item.Id }) |*@
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

COMP4900_SOCE_WebApp/Views/Users/ManageUserRoles.cshtml
@model Microsoft.AspNet.Identity.EntityFramework.IdentityUser

@{
    ViewBag.Title = "ManageUserRoles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Manage User Roles</h2>

<div class="btn-group" role="group" aria-label="...">
    <input type="submit" value="Back" class="btn btn-default" onclick="location.href='@Url.Action("Index", "Users")'">
    <input type="submit" value="Create" class="btn btn-default" onclick="location.href='@Url.Action("Create", "Users")'">
</div>
@*@Html.ActionLink("Back", "Index", "Users")
@Html.ActionLink("Create New Role", "Create", "Roles")*@

<hr />

@if (ViewBag.Message != null)
{
    <div>
        <p>@ViewBag.Message </p>
    </div>
}

<h3>Role Add to User</h3>
@using (Html.BeginForm("RoleAddToUser", "Users"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <p>
        Username : @Html.DropDownList("UserName", (IEnumerable<SelectListItem>)ViewBag.UserDropdownlist, htmlAttributes: new { @class = "form-control" })
        Role Name: @Html.DropDownList("RoleName", (IEnumerable<SelectListItem>)ViewBag.RoleDropdownlist, htmlAttributes: new { @class = "form-control" })
    </p>

    <input type="submit" value="Save" />
}
<hr />
<h3>Get Roles for a User</h3>
@using (Html.BeginForm("GetRoles", "Users"))
{
    @Html.AntiForgeryToken()
    <p>
        Username : @Html.DropDownList("UserName", (IEnumerable<SelectListItem>)ViewBag.UserDropdownlist, htmlAttributes: new { @class = "form-control" })
        <input type="submit" value="Get Roles for this User" />
    </p>
}
@if (ViewBag.UserRoles != null)
{
    <div style="background-color:yellow;">
        <h3>Roles for this user </h3>
        <ol>
            @foreach (string s in ViewBag.UserRoles)
            {
                <li>@s</li>
            }
        </ol>
    </div>
}
<hr />
<h3>Delete A User from a Role</h3>
@using (Html.BeginForm("DeleteRoleForUser", "Users"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <p>
        Username : @Html.DropDownList("UserName", (IEnumerable<SelectListItem>)ViewBag.UserDropdownlist, htmlAttributes: new { @class = "form-control" })
        Role Name: @Html.DropDownList("RoleName", (IEnumerable<SelectListItem>)ViewBag.RoleDropdownlist, htmlAttributes: new { @class = "form-control" })
    </p>

    <input type="submit" value="Delete this user from Role" />
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}